spring.application.name=TODO
spring.profiles.default=dev

spring.jpa.hibernate.ddl-auto=none

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret

spring.web.locale=en_US