DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS todo;

CREATE TABLE "user"
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT pk_user_id PRIMARY KEY (user_id)
);

CREATE TABLE todo
(
    todo_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255) NOT NULL,
    comment VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    expiry_date DATE,
    user_id BIGINT,
    CONSTRAINT fk_todo_user
        FOREIGN KEY (user_id)
            REFERENCES "user"(user_id)
            ON DELETE CASCADE
);